Fix typedef redefinition error, switch to PAL implemented _snprintf_s.
```
[  359s] In file included from /home/abuild/rpmbuild/BUILD/heaptrack-1.1.0/profiler/profiler/src/profiler.cpp:2:
[  359s] In file included from /home/abuild/rpmbuild/BUILD/heaptrack-1.1.0/profiler/profiler/src/profiler.h:4:
[  359s] /usr/share/dotnet.tizen/netcoreapp/src/pal/inc/pal.h:4591:22: error: typedef redefinition with different types ('struct _FILE' vs 'struct _IO_FILE')
[  359s] typedef struct _FILE FILE;
[  359s]                      ^
```